# Generated by Django 3.2.8 on 2022-05-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('DNI', models.IntegerField(max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=64)),
                ('apellidos', models.CharField(max_length=100)),
                ('fechaNac', models.DateField()),
            ],
        ),
    ]
