# Generated by Django 3.2.8 on 2022-05-09 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_alter_usuario_dni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='fechaNac',
        ),
    ]
