# Generated by Django 3.2.8 on 2022-05-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_remove_usuario_fechanac'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fechaNac',
            field=models.DateField(auto_now=True),
        ),
    ]
