# Generated by Django 3.2.8 on 2022-05-09 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0006_alter_usuario_fechanac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fechaNac',
            field=models.DateField(),
        ),
    ]
