# Generated by Django 3.2.8 on 2022-05-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0007_alter_usuario_fechanac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='DNI',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellidos',
            field=models.CharField(max_length=100, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fechaNac',
            field=models.DateField(null=True, verbose_name='FechaNac'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=64, verbose_name='Nombre'),
        ),
    ]
